services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=FAWKES
      - MYSQL_USER=james
      - MYSQL_PASSWORD=EFN2026
      - MYSQL_ROOT_PASSWORD=epsteinForever2026
    ports:
      - 3367:3306
